# Generated by Django 4.2.4 on 2023-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Texto"), ("number", "Número")],
                        max_length=255,
                        verbose_name="Tipo",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aprovada", "Aprovada"),
                            ("Negada", "Negada"),
                            ("Aguardando análise", "Aguardando análise"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("values", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Proposta",
                "verbose_name_plural": "Propostas",
            },
        ),
        migrations.CreateModel(
            name="ProposalFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fields", models.ManyToManyField(to="proposal.fields")),
            ],
            options={
                "verbose_name": "Campos da proposta",
                "verbose_name_plural": "Campos da proposta",
            },
        ),
    ]
