# Generated by Django 4.2.4 on 2023-08-29 12:14

from django.db import migrations


def create_fields(apps, schema_editor):
    Fields = apps.get_model("proposal", "Fields")
    ProposalFields = apps.get_model("proposal", "ProposalFields")
    
    fields = [
        Fields(**{"name": "cpf", "label": "CPF", "type": "text"}),
        Fields(**{"name": "value", "label": "Valor da proposta", "type": "number"}),
    ]
    Fields.objects.bulk_create(fields, ignore_conflicts=True)
    instances = Fields.objects.all()
    
    instance, created = ProposalFields.objects.get_or_create()
    instance.fields.set(instances)

class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_fields)
    ]
